apiVersion: apps/v1
kind: Deployment
metadata:
  name: mandigo-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mandigo-frontend
  template:
    metadata:
      labels:
        app: mandigo-frontend
    spec:
      containers:
      - name: frontend
        # PASTE YOUR FULL ECR URI BELOW, REPLACING THE PLACEHOLDER:
        image: 526955697030.dkr.ecr.ap-south-1.amazonaws.com/mandigo-frontend:596377438eb073bde563bb73ad4cba2762119872
        ports:
        - containerPort: 80
