apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mandigo-frontend-secure
  namespace: default
spec:
  entryPoints:
    - websecure
  tls:
    certResolver: le
    domains:
      - main: projectbyradhe.xyz
  routes:
    - match: Host(`projectbyradhe.xyz`)
      kind: Rule
      services:
        - name: mandigo-frontend-service
          port: 80
