# Frontend SPA — Nginx-served Vite bundle, namespace `default`.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mandigo-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/theradheshyampatil/mandigo-gitops
    targetRevision: HEAD
    path: k8s/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
