name: 'Terraform Apply - Build AWS ECR'

on:
  push:
    paths:
      - 'terraform/**'      # Only run when Terraform files change
    branches:
      - main                # Only run on the main branch

jobs:
  deploy-infrastructure:
    name: 'Create MandiGo ECR Repositories'
    runs-on: ubuntu-latest  # Rent a temporary Ubuntu computer from GitHub

    steps:
      # Step 1: Download our code from GitHub
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log into AWS using the keys you gave GitHub
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Step 3: Install Terraform on the GitHub computer
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/ecr

      # Step 5: Tell Terraform to build the ECR in AWS (-auto-approve means don't ask for human permission)
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform/ecr
